server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'task_management'
  url: 'postgres://lgaxyywv:3UrfbQ1zx2RKYlM8sImwIboRHH4nmsFO@kandula.db.elephantsql.com:5432/lgaxyywv'

jwt:
  expiresIn: 3600
